name: CI Builds

on:
  release:
    types:
      - created

jobs:
  build_mac:
    name: Build macOS app
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Enable Flutter support for macOS
        run: flutter config --enable-macos-desktop
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - name: Install bash 5
        run: brew install bash
      - name: Export brew path
        run: export PATH="/usr/local/bin:$PATH"
      - name: Build
        run: |
          PATH=/usr/local/bin:$PATH tools/build_macos.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/macos/Registro-*
          generate_release_notes: true
  build_web:
    name: Build web app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Enable Flutter support for web
        run: flutter config --enable-web
      - name: Build
        run: tools/build_web.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/web/Registro-*
          generate_release_notes: true
