# yaml-language-server: $schema=https://github.com/SchemaStore/schemastore/raw/master/src/schemas/json/github-workflow.json
name: Build app

on:
  push:
    branches:
      - "releases/**"
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        flavor: [release]
    runs-on: macos-11
    steps:
      - name: Get the target version from the tag/branch name
        id: create_tag
        run: |
          tag=$(grep -q 'refs/heads/releases/' <<< ${{ github.ref }} && echo ${{ github.ref }} | sed 's_refs/heads/releases/__' || echo ${{ github.ref }} | sed 's_refs/tags/v__')
          echo "::set-output name=tag::$tag"
      - name: Current date
        id: get_date
        run: |
          date=$(date +"%Y-%m-%d @ %H:%M:%S")
          echo "::set-output name=date::$date"
      - name: Get the timestamp for the build number
        id: get_timestamp
        run: |
          date=$(date '+%s')
          echo "::set-output name=timestamp::$date"

      - uses: actions/checkout@v2

      - name: "[Android] Get the absolute location of the keystore file"
        id: get_keystore
        run: |
          function abspath() {
            # generate absolute path from relative path
            # $1     : relative filename
            # return : absolute path
            if [ -d "$1" ]; then
              # dir
              (cd "$1"; pwd)
            elif [ -f "$1" ]; then
              # file
              if [[ $1 = /* ]]; then
                echo "$1"
              elif [[ $1 == */* ]]; then
                echo "$(cd "${1%/*}"; pwd)/${1##*/}"
              else
                echo "$(pwd)/$1"
              fi
            fi
          }

          echo "::set-output name=keystore::$(abspath $GITHUB_WORKSPACE/private/upload-keystore.jks)"
      - name: "[Android] Write the key.properties file"
        id: write_key_properties
        run: |
          echo "storePassword=${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}\nkeyPassword=${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}\nkeyAlias=upload\nstoreFile=${{ steps.get_keystore.outputs.keystore }}" > $GITHUB_WORKSPACE/android/key.properties

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter config --enable-macos-desktop
      - name: "Build macOS ${{ matrix.flavor }} app"
        run: flutter build macos --${{ matrix.flavor }} --build-number ${{ steps.get_timestamp.outputs.timestamp }} --build-name=${{ steps.create_tag.outputs.tag }}
      - name: "Build Android ${{ matrix.flavor }} APK"
        run: flutter build apk --${{ matrix.flavor }} --build-number ${{ steps.get_timestamp.outputs.timestamp }} --build-name=${{ steps.create_tag.outputs.tag }}
      - name: "Build Android ${{ matrix.flavor }} App Bundle"
        run: flutter build appbundle --${{ matrix.flavor }} --build-number ${{ steps.get_timestamp.outputs.timestamp }} --build-name=${{ steps.create_tag.outputs.tag }}

      - name: Get the name of the output artifact folder for the macOS build
        id: folder_name
        run: |
          folder=$(awk '{for(j=1;j<=NF;j++){ $j=toupper(substr($j,1,1)) substr($j,2) }}1' <<<"${{ matrix.flavor }}")
          echo "::set-output name=folder::$folder"
      - name: Zip macOS app
        run: ditto -c -k --sequesterRsrc --keepParent ./build/macos/Build/Products/${{ steps.folder_name.outputs.folder }}/Registro.app "Registro-macOS-${{ matrix.flavor }}.zip"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "v${{ steps.create_tag.outputs.tag }}"
          name: "Release ${{ steps.create_tag.outputs.tag }}"
          files: |
            Registro-macOS-${{ matrix.flavor }}.zip
            build/app/outputs/bundle/${{ matrix.flavor }}/app-${{ matrix.flavor }}.aab
            build/app/outputs/flutter-apk/app-${{ matrix.flavor }}.apk
          body: |
            Built on ${{ steps.get_date.outputs.date }}

      - name: Cleanup
        continue-on-error: true
        run: |
          rm -rf $GITHUB_WORKSPACE/android/key.properties
          rm -rf $GITHUB_WORKSPACE/private/upload-keystore.jks
