# Taken from https://github.com/acidanthera/MaciASL and edited
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

# env:
#   PROJECT_TYPE: TOOL

jobs:
  appcast:
    name: Set Appcast
    needs: build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
      # SIGNATURE_FOR_SIGNING: ${{ secrets.SIGNATURE_FOR_SIGNING }}
    # if: github.event_name == 'release'
    steps:
      - name: Get Sparkle 1.26
        run: |
          curl -L -s "https://github.com/sparkle-project/Sparkle/releases/download/1.26.0/Sparkle-1.26.0.tar.xz" -o Sparkle.tar.xz || exit 1
          tar -xf Sparkle.tar.xz || exit 1
      - name: Get Information & Sign
        run: |
          TAG_VER=${GITHUB_REF/refs\/tags\//}
          DATE=$(date -R)
          ./bin/generate_appcast -o appcast.xml --download-url-prefix https://github.com/Samplasion/reaxios/releases/download/${TAG_VER}/ build/Release || exit 1
      - name: Commit Appcast
        run: |
          # The 41898282 identifier comes from the GitHub Actions API: https://api.github.com/users/github-actions%5Bbot%5D.
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan appcast
          git add appcast.xml
          git commit appcast.xml -m "Update Appcast"
          git push --set-upstream origin appcast --force
